[project]
name = "live-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastai>=2.8.5",
    "imutils>=0.5.4",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "torch>=2.9.0",
]
